# Based on Evil Martians configuration:
# https://gist.githubusercontent.com/palkan/623c0816b05ed246bfe0cb406050990a/raw/7b3314e9bc9431fb23d29019261edec47df0ad10/.rubocop_rspec.yml

require:
  - rubocop-rspec

# Disable all cops by default,
# only enable those defined explcitly in this configuration file
RSpec:
  Enabled: false

RSpec/Focus:
  Enabled: true

RSpec/EmptyExampleGroup:
  Enabled: true

RSpec/EmptyLineAfterExampleGroup:
  Enabled: true

RSpec/EmptyLineAfterFinalLet:
  Enabled: true

RSpec/EmptyLineAfterHook:
  Enabled: true

RSpec/EmptyLineAfterSubject:
  Enabled: true

RSpec/HookArgument:
  Enabled: true

RSpec/HooksBeforeExamples:
  Enabled: true

RSpec/ImplicitExpect:
  Enabled: true

RSpec/IteratedExpectation:
  Enabled: true

RSpec/LetBeforeExamples:
  Enabled: true

RSpec/MissingExampleGroupArgument:
  Enabled: true

RSpec/ReceiveCounts:
  Enabled: true

RSpec/Capybara/CurrentPathExpectation:
  Enabled: true

RSpec/FactoryBot/AttributeDefinedStatically:
  Enabled: true

RSpec/FactoryBot/CreateList:
  Enabled: true
